### PR TITLE
add sndio support

### PR DESCRIPTION
**Pull request by jg1uaa**

### CODE REVIEW

**Comment by jg1uaa** [comment]
Currently supporting PortAudio enables using direwolf on OpenBSD, but PortAudio is dedicated for single audio device not for multiple.
Even if PA_SNDIO_AUDIODEVICES variable can handle multiple devices (http://openbsd-archive.7691.n7.nabble.com/audio-portaudio-svn-Add-support-for-multiple-sndio-devices-td358622.html),  it is difficult to select device for input/output. Both specifying PA_SNDIO_AUDIODEVICE and ADEVICE in direwolf.conf is needed. 

Therefore, native sndio support is strongly required. And this will help other *BSD users such as NetBSD and FreeBSD. Some Linux distribution has sndio support, so this code can be tested with modified CMakeLists.txt.

**Comment by jg1uaa** [comment]
I will resend pull request to dev branch, so I close this request (to master).

**Comment by wb2osz** [comment]
Please be patient.  I have a job, family, and other things I need to take care of.  If something is in the queue I will get to it eventually.  Thanks.

**Comment by jg1uaa** [comment]
Sorry, I found a serious trouble that sndio-supported direwolf crashes without any messages when unplugging USB audio or device error. So I had to once close this request.

Now I reconstructed sndio support on dev branch, it looks no problem. I will resend PR within a few days, please reveiw new code if you have enough time. Regards,

postscript:
be careful to use direwolf with cheap USB audio device, it is sometimes unreliable...

**Pull request closed without merging**
