### PR TITLE
github actions implementation

### PR DESCRIPTION
**Pull request by ra1nb0w**
This is a start commit to use github actions to test every new commit on linux, windows and macOS.
Can be expanded to build every release/tag and push it to the right github section.

### CODE REVIEW

**Comment by wb2osz** [comment]
I was in the process of merging this to the "dev" branch and noticed something.

Should "workflows/main.yml" be ".github/workflows/main.yml" instead?

**Comment by ra1nb0w** [comment]
sorry, my mistake. fixed

**Comment by ra1nb0w** [comment]
- macOS arise the following bug https://github.com/wb2osz/direwolf/issues/330
- now I am re-testing windows because they changed versions and therefore requires some changes.

**Comment by ra1nb0w** [comment]
- windows 2019 32bit arises the following error `multiple definition of `re_syntax_options'` see https://github.com/wb2osz/direwolf/runs/6604898435?check_suite_focus=true

**Comment by ra1nb0w** [comment]
ping

**Comment by wb2osz** [comment]
Thank you for helping with this.
I tried but could not figure it out.
Let's merge it and see what happens.....

**Pull request merged**
