### PR TITLE
Adjusting github workflows for CodeQL testing

### PR DESCRIPTION
**Pull request by RafaelGCPP**
- Updated CodeQL action versions to v3
- Updated minimum CMake requirement to 3.5
- Split CodeQL analysis in two files, one for C++ and one for Python, as the "run" step was not being effective in the Python testing

With those modifications, now the code is tested and validated.

### CODE REVIEW

**Comment by RafaelGCPP** [comment]
Related to Issue #521

**Comment by wb2osz** [comment]
Thank you for these updates.
I've merged them into the dev branch and am awaiting the results.

73,
John WB2OSZ

**Comment by wb2osz** [comment]
It turns out this needs to be on master branch.
Merged to master branch.

**Review by wb2osz — COMMENTED** [review]
I'm a little concerned about bumping up the minimum cmake version because a very old system might not have it.  I guess we can decrease it if anyone yells and doesn't have the ability to upgrade.

**Comment by RafaelGCPP** [comment]
Feel free to do so. The bumping in the CMake version was a collateral on my side. My CMake warned about not supporting the older version, so I bumped it up, but it is not a big deal at all.

**Pull request merged**
