### PR TITLE
fix compilation on musl

### LINKED ISSUE #150: Compile error in Alpine Linux 3.7
OS: Alpine Linux 3.7
gcc-6.4.0-r5
linux-headers-4.4.6-r2
alsa-lib-dev-1.1.4.1-r2
...
direwolf-1.5-beta2

Same error on both x86_64 and armv6l (raspberry pi)

```
/tmp/direwolf-1.5-beta2 # make
gcc -O3 -pthread -Igeotranz -D_XOPEN_SOURCE=600 -D_DEFAULT_SOURCE=1 -Wall -D_BSD_SOURCE -ffast-math -DUSE_ALSA   -c -o direwolf.o direwolf.c
/usr/include/string.h:83:45: error: expected declaration specifiers or '...' before string constant
 size_t strlcat (char *, const char *, size_t);
                                             ^
In file included from direwolf.c:41:0:
direwolf.h:294:65: error: expected declaration specifiers or '...' before '__func__'
 #define strlcat(dst,src,siz) strlcat_debug(dst,src,siz,__FILE__,__func__,__LINE__)
                                                                 ^
/usr/include/string.h:83:45: error: expected declaration specifiers or '...' before numeric constant
 size_t strlcat (char *, const char *, size_t);
                                             ^
/usr/include/string.h:84:45: error: expected declaration specifiers or '...' before string constant
 size_t strlcpy (char *, const char *, size_t);
                                             ^
direwolf.h:293:65: error: expected declaration specifiers or '...' before '__func__'
 #define strlcpy(dst,src,siz) strlcpy_debug(dst,src,siz,__FILE__,__func__,__LINE__)
                                                                 ^
/usr/include/string.h:84:45: error: expected declaration specifiers or '...' before numeric constant
 size_t strlcpy (char *, const char *, size_t);
                                             ^
In file included from /usr/include/fortify/stdio.h:23:0,
                 from direwolf.c:45:
/usr/include/fortify/string.h:156:1: error: 'strlcat' undeclared here (not in a function)
 _FORTIFY_FN(strlcat) size_t strlcat(char *__d, const char *__s, size_t __n)
 ^
In file included from direwolf.c:50:0:
/usr/include/fortify/string.h: In function 'strlcat':
/usr/include/fortify/string.h:162:9: error: called object '__orig_strlcat' is not a function or function pointer
  return __orig_strlcat(__d, __s, __n);
         ^~~~~~~~~~~~~~
In file included from /usr/include/fortify/stdio.h:23:0,
                 from direwolf.c:45:
/usr/include/fortify/string.h:156:1: note: declared here
 _FORTIFY_FN(strlcat) size_t strlcat(char *__d, const char *__s, size_t __n)
 ^
/usr/include/fortify/string.h: At top level:
/usr/include/fortify/string.h:165:1: error: 'strlcpy' undeclared here (not in a function)
 _FORTIFY_FN(strlcpy) size_t strlcpy(char *__d, const char *__s, size_t __n)
 ^
In file included from direwolf.c:50:0:
/usr/include/fortify/string.h: In function 'strlcpy':
/usr/include/fortify/string.h:171:9: error: called object '__orig_strlcpy' is not a function or function pointer
  return __orig_strlcpy(__d, __s, __n);
         ^~~~~~~~~~~~~~
In file included from /usr/include/fortify/stdio.h:23:0,
                 from direwolf.c:45:
/usr/include/fortify/string.h:165:1: note: declared here
 _FORTIFY_FN(strlcpy) size_t strlcpy(char *__d, const char *__s, size_t __n)
 ^
make: *** [<builtin>: direwolf.o] Error 1
```

### PR DESCRIPTION
**Pull request by classabbyamp**
this should allow for compilation on musl libc

possibly fixes #150

### CODE REVIEW

**Comment by wb2osz** [comment]
I have a simpler solution to the first part.  Simply use:

	    qsort (tocalls, num_tocalls, sizeof(struct tocalls_s), tocall_cmp);

gcc does not complain about the missing type cast.  Don't recall why I put it in there.

**Comment by wb2osz** [comment]
cmake tests whether the runtime library contains strlcpy and strlcat.
This determines whether we include our own copy.
We should be able to use result of that test rather than listing all of the possible operating system variations.

To be continued...

**Comment by classabbyamp** [comment]
updated to address the first comment.

> cmake tests whether the runtime library contains strlcpy and strlcat

I couldn't find this in any of the cmake files. Can you point it out to me?

**Comment by wb2osz** [comment]
The "dev" development branch already has this in direwolf.h

#ifndef HAVE_STRLCPY	// Need to supply our own.
...
#define strlcpy(dst,src,siz) strlcpy_debug(dst,src,siz)
size_t strlcpy_debug(char *__restrict__ dst, const char *__restrict__ src, size_t siz);
...
#endif


Were you using the "master" branch?

**Comment by classabbyamp** [comment]
yes I was basing the PR on master

**Comment by wb2osz** [comment]
Try the "dev" branch.
My convention is to do development on "dev" and push to master when I have something stable.

**Comment by wb2osz** [comment]
Oops. I meant merge to master.  Need to be more careful about terminology.

**Comment by wb2osz** [comment]
Thanks for helping to make this more portable.

**Comment by classabbyamp** [comment]
No problem! I'm trying to get direwolf accepted into void linux's repositories in void-linux/void-packages#37147

**Pull request closed without merging**
