### PR TITLE
Add feature to Timestamp activity in stdout using -T in command line.

### PR DESCRIPTION
**Pull request by CInsights**
Only added for packet traffic (not applied to output from IG).

Standard time format is specified after -T in quoted string.
Added to dev branch.

### CODE REVIEW

**Comment by jeremymturner** [comment]
This would be very helpful!

**Comment by wb2osz** [comment]
I added something very similar to this in the "dev" branch.  It applies to both received and transmitted packets.

**Comment by CInsights** [comment]
Thanks John.
I think this will satisfy the guys who I've done RPi implementations for.
They bugged me into doing the original patch.
FYI I've also re-written autostart into a menu based control system built with BASH and using TMUX instead of SCREEN.
This has a control pane with menu and stats display capability + a scrolling pane for activity display.
If you'd like to have a play let me know.

Cheers,

Bob - VK2GJ

**Comment by jeremymturner** [comment]
That sounds like an awesome feature. I too use tmux to launch direwolf.

Jeremy / KO6RM

-- 
Jeremy Turner

**Comment by CInsights** [comment]
Hi Jeremy,
I'm happy to share but don't have the time to manage having the code up on Github and deal with fixes/changes.
The code is "good enough" for the few hams I did RPi IGate implementations for (they wanted to get of ageing PCs running IGates).
There is plenty of scope for "improvement" in the code :-)

Cheers,

Bob - VK2GJ

image

**Pull request closed without merging**
